connection_num: 1000
connection_num_per_thread: 50
message_num_per_connection: 1
keep_alive: 600
username: null
password: null
# iot.eclipse.org
server_url: iot.eclipse.org
server_port: 1883
server_protocol: tcp
publish_topic: paho/iot/10086
subscribe_topic: paho/iot/10086
qos: 1

# logging
logging.level.root: WARN
logging.level.org.mqtt: ERROR
#logging.path: D:\\WorkData\\log