package org.mqtt.client.event;

public enum EventType {

	DIS_CONNECT,
	CONNECT_SUCCESS,
	CONNECT_FAILURE,
	SUBSCRIBE_SUCCESS,
	SUBSCRIBE_FAILURE,
	PUBLISH_SUCCESS,
	PUBLISH_FAILURE,
	MESSAGE_ARRIVE,
	UNSUBSCRIBE_SUCCESS;
}
